export type AiAgentTemplateContext = {
  template: "vite" | "next"
  alias: string
  componentsPath: string
  uiPath: string
  hooksPath: string
  utilsPath: string
  globalCssPath: string
}

export type AiAgentTemplateFile = {
  path: string
  content: string
}

const skill = (name: string, description: string, body: string) => `---\nname: ${name}\ndescription: ${description}\n---\n\n${body.trim()}\n`

export function createAiAgentTemplateFiles(context: AiAgentTemplateContext): AiAgentTemplateFile[] {
  const framework = context.template === "next" ? "Next.js App Router" : "React + Vite"

  const agents = `# AGENTS.md\n\nThis repository is a ${framework} application initialized with Tembro.\n\n## Repository map\n\n- Component source root: \`${context.componentsPath}\`\n- UI primitives: \`${context.uiPath}\`\n- Hooks: \`${context.hooksPath}\`\n- Shared utilities: \`${context.utilsPath}\`\n- Global theme CSS: \`${context.globalCssPath}\`\n- Tembro configuration: \`tembro.json\`\n- Agent playbooks: \`.agents/skills/*/SKILL.md\`\n\n## Working rules\n\n1. Inspect existing components and nearby patterns before changing code.\n2. Prefer improving or composing existing Tembro components over adding duplicate public components.\n3. Keep product and business logic outside reusable UI primitives.\n4. Preserve controlled and uncontrolled APIs when both are meaningful.\n5. Cover loading, empty, error, disabled, readonly, responsive, and keyboard states.\n6. Keep heavy engines lazy and source-copy only when possible.\n7. Keep aliases consistent with \`${context.alias}\` and \`tembro.json\`.\n8. Run focused checks first and full validation before final handoff.\n9. Never claim an integration or import/export feature works unless it is implemented and validated.\n10. Keep changes scoped, reviewable, and documented.\n\n## Tembro commands\n\n- \`npx tembro list\`\n- \`npx tembro add <component>\`\n- \`npx tembro theme\`\n- \`npx tembro init --defaults\`\n\n## Skill routing\n\n- UI component work: \`.agents/skills/tembro-component-development/SKILL.md\`\n- Design-system work: \`.agents/skills/design-system-governance/SKILL.md\`\n- Accessibility: \`.agents/skills/accessibility-review/SKILL.md\`\n- Testing: \`.agents/skills/testing-and-validation/SKILL.md\`\n- Architecture and performance: \`.agents/skills/frontend-architecture/SKILL.md\`\n- Review and delivery: \`.agents/skills/code-review-and-delivery/SKILL.md\`\n\n## Definition of done\n\nImplementation, states, accessibility, responsive behavior, documentation, and validation must agree.\n`

  const files: AiAgentTemplateFile[] = [
    { path: "AGENTS.md", content: agents },
    {
      path: ".agents/README.md",
      content: `# AI agent skills\n\nGenerated by \`tembro init\`. Each playbook lives in \`.agents/skills/<name>/SKILL.md\`. Customize these files for the project; re-running init preserves existing files unless overwrite is enabled.\n`,
    },
    {
      path: ".agents/skills/tembro-component-development/SKILL.md",
      content: skill("tembro-component-development", "Build and improve reusable React components with Tembro source-copy conventions.", `# Tembro component development\n\n1. Search for an existing surface before creating a new component.\n2. Decide whether the feature belongs in a primitive, composed component, pattern, block, or app layer.\n3. Preserve compatible APIs and use typed callbacks.\n4. Add refs only for meaningful imperative behavior.\n5. Prefer slots and render props over hard-coded product UI.\n6. Support controlled and uncontrolled state where appropriate.\n7. Cover loading, empty, error, disabled, readonly, permission, reconnect, and cleanup states.\n8. Update the matching demo and API docs.\n9. Validate keyboard, responsive behavior, and dependency impact.\n\nPaths: \`${context.componentsPath}\`, \`${context.uiPath}\`, \`${context.hooksPath}\`, \`${context.utilsPath}\`.`),
    },
    {
      path: ".agents/skills/design-system-governance/SKILL.md",
      content: skill("design-system-governance", "Maintain tokens, visual consistency, taxonomy, and theme behavior.", `# Design-system governance\n\n- Use semantic tokens from \`${context.globalCssPath}\`.\n- Preserve light and dark themes.\n- Reuse primitives from \`${context.uiPath}\`.\n- Keep variants intentional and avoid one-off public variants.\n- Review hover, active, focus, disabled, destructive, loading, and selected states.\n- Check mobile and desktop density.\n- Keep names and categories stable because they are public API.`),
    },
    {
      path: ".agents/skills/accessibility-review/SKILL.md",
      content: skill("accessibility-review", "Audit semantics, keyboard behavior, focus, announcements, and accessible states.", `# Accessibility review\n\n- Prefer semantic HTML before ARIA.\n- Give every control an accessible name.\n- Provide keyboard equivalents for pointer actions.\n- Keep focus visible and predictable.\n- Associate errors with affected fields.\n- Do not use color as the only signal.\n- Keep touch targets usable.\n- Respect reduced motion.\n- Test loading, empty, error, disabled, readonly, and selected states with keyboard navigation.`),
    },
    {
      path: ".agents/skills/testing-and-validation/SKILL.md",
      content: skill("testing-and-validation", "Run focused tests, browser checks, builds, and regression validation.", `# Testing and validation\n\n1. Type-check the touched surface.\n2. Run focused unit or render tests.\n3. Test keyboard and state transitions.\n4. Check responsive behavior.\n5. Use browser smoke tests for browser APIs and heavy engines.\n6. Run the production build.\n7. Run the full suite before release when practical.\n\nReport exactly what passed, failed, or could not run.`),
    },
    {
      path: ".agents/skills/frontend-architecture/SKILL.md",
      content: skill("frontend-architecture", "Guide React architecture, boundaries, data flow, performance, and dependency decisions.", `# Frontend architecture\n\n- Keep reusable interaction in components and domain rules in application modules.\n- Keep server-only logic outside client components.\n- Lazy-load heavy engines.\n- Keep state close to its owner.\n- Avoid unnecessary effect-driven synchronization.\n- Clean observers, listeners, timers, streams, workers, and subscriptions.\n- Measure bundle impact before adding dependencies.\n\nFramework: ${framework}.`),
    },
    {
      path: ".agents/skills/code-review-and-delivery/SKILL.md",
      content: skill("code-review-and-delivery", "Review changes and prepare accurate commits and pull-request handoffs.", `# Code review and delivery\n\nReview in this order: correctness, API compatibility, accessibility, state handling, cleanup, performance, dependency impact, docs, then style.\n\nKeep commits scoped. Include validation results and remaining limitations in PRs. Verify generated and source-copy assets are packaged. Never mark work production-ready when required browser or consumer-fixture checks did not run.`),
    },
  ]

  return files
}
