import type { ComponentName } from "./registry"

export type ComponentStatus = "stable" | "preview" | "experimental" | "internal"

export const registryStatus: Partial<Record<ComponentName, ComponentStatus>> = {
  utils: "internal",

  button: "stable",
  input: "stable",
  textarea: "stable",
  checkbox: "stable",
  switch: "stable",
  badge: "stable",
  card: "stable",
  dialog: "stable",
  "dropdown-menu": "stable",
  popover: "stable",
  select: "stable",
  table: "stable",
  "radio-group": "stable",
  "scroll-box": "stable",
  "right-click-menu": "stable",
  accordion: "stable",
  kbd: "stable",

  "dialog-actions": "stable",
  "modal-shell": "stable",
  "confirm-dialog": "stable",
  "sheet-shell": "stable",
  "alert-dialog": "stable",
  drawer: "stable",
  overlay: "stable",
  pagination: "stable",

  "input-decorator": "internal",
  "input-value": "internal",
  "clearable-input": "internal",
  "search-input": "internal",
  "password-input": "internal",
  "number-input": "internal",
  "date-input": "internal",
  "date-range-input": "internal",
  "money-input": "internal",
  "quantity-input": "internal",
  "masked-input": "internal",
  "phone-input": "internal",
  "simple-select": "internal",
  "async-select": "preview",
  inputs: "internal",

  "form-field-shell": "internal",
  "form-input": "internal",
  "form-select": "internal",
  "form-async-select": "internal",
  "form-textarea": "internal",
  "form-switch": "internal",
  form: "internal",

  "loading-state": "stable",
  feedback: "stable",
  "description-list": "stable",
  progress: "stable",
  result: "stable",
  timeline: "stable",
  "metric-grid": "stable",
  "info-card": "stable",
  "activity-feed": "stable",
  display: "stable",
  "action-menu": "stable",
  actions: "stable",
  "stat-card": "internal",
  "app-header": "internal",
  sidebar: "stable",
  "app-sidebar": "internal",
  "sidebar-nav": "internal",
  breadcrumbs: "stable",
  "page-container": "internal",
  layout: "stable",
  "filter-bar": "stable",
  filters: "stable",

  "data-table-toolbar": "internal",
  "data-table-pagination": "internal",
  "data-table-column-visibility-menu": "internal",
  "data-table-select-column": "internal",
  "data-table-sortable-header": "internal",
  "data-table-row-actions": "internal",
  "data-table-actions-column": "internal",
  "data-table-bulk-actions": "internal",
  "data-table-view-presets": "internal",
  "data-table-saved-filters": "internal",
  "data-table": "preview",

  calendar: "preview",
  "date-picker": "preview",
  "date-range-picker": "preview",
  "calendar-kit": "preview",
  "file-upload": "preview",
  "image-upload": "preview",
  upload: "preview",
  stepper: "preview",
  wizard: "preview",
  "wizard-kit": "preview",
  toast: "preview",
  notifications: "preview",
  "command-palette": "preview",
  command: "preview",
  "resource-page": "preview",
  "resource-detail-page": "preview",
  patterns: "preview",

  "use-session-storage-state": "stable",
  "use-before-unload-when-dirty": "stable",
  "use-is-mobile": "stable",
  "use-disclosure": "stable",
  "use-debounce": "stable",
  "use-data-table-view-state": "preview",
  hooks: "stable",

  dashboard: "preview",
  all: "preview",

  "trend-card": "preview",
  "comparison-card": "preview",
  "delta-badge": "preview",
  "data-list": "preview",
  "inline-editable": "preview",
  "command-bar": "preview",
  "saved-filter-select": "preview",
  "notification-center": "preview",
}

export function getRegistryStatus(name: ComponentName): ComponentStatus {
  return registryStatus[name] ?? "preview"
}
