import type { ComponentName } from "./registry"

export type ComponentStatus = "stable" | "preview" | "experimental" | "internal"

export const registryStatus: Partial<Record<ComponentName, ComponentStatus>> = {
  utils: "internal",

  button: "stable",
  input: "stable",
  textarea: "stable",
  checkbox: "stable",
  switch: "stable",
  badge: "stable",
  card: "stable",
  dialog: "stable",
  "dropdown-menu": "stable",
  popover: "stable",
  select: "stable",
  table: "stable",
  "radio-group": "stable",
  accordion: "stable",
  "simple-select": "internal",
  combobox: "preview",
  "scroll-box": "stable",
  "right-click-menu": "stable",
  kbd: "stable",

  "dialog-actions": "internal",
  "modal-shell": "internal",
  "confirm-dialog": "stable",
  "alert-dialog": "stable",
  drawer: "stable",
  overlay: "stable",
  pagination: "stable",

  "async-select": "preview",
  "color-picker": "stable",
  "signature-pad": "preview",

  "form-field-shell": "preview",
  "form-input": "preview",
  "form-select": "preview",
  "form-textarea": "preview",
  "form-switch": "preview",
  "form-date-range-input": "preview",
  "form-date-picker": "preview",
  "form-date-range-picker": "preview",
  form: "preview",

  "loading-state": "stable",
  feedback: "stable",
  "description-list": "stable",
  progress: "stable",
  timeline: "stable",
  "info-card": "stable",
  "activity-feed": "stable",
  display: "stable",
  "action-menu": "stable",
  actions: "stable",
  "app-header": "internal",
  sidebar: "stable",
  breadcrumbs: "stable",
  layout: "stable",
  "filter-bar": "stable",
  filters: "stable",

  "data-table": "preview",
  "data-table-actions-column": "internal",
  "table-export-menu": "internal",
  "table-import-button": "internal",

  calendar: "preview",
  "date-picker": "preview",
  "date-range-picker": "preview",
  "calendar-kit": "preview",
  "file-upload": "preview",
  "image-upload": "preview",
  upload: "preview",
  stepper: "preview",
  wizard: "preview",
  "wizard-kit": "preview",
  toast: "preview",
  notifications: "preview",
  "command-palette": "preview",
  command: "preview",
  "hover-card": "stable",
  menubar: "preview",
  "navigation-menu": "preview",
  patterns: "preview",

  "use-session-storage-state": "stable",
  "use-before-unload-when-dirty": "stable",
  "use-is-mobile": "stable",
  "use-disclosure": "stable",
  "use-debounce": "stable",
  "use-data-table-view-state": "preview",
  hooks: "stable",

  dashboard: "preview",
  all: "preview",

  "inline-editable": "preview",
  "saved-filter-select": "preview",
  "notification-center": "preview",
  "calendar-scheduler": "preview",
  "dual-list-picker": "preview",
  "resizable-panel": "preview",
  "rich-text-editor": "preview",
  "image-cropper": "preview",
  "qr-code": "stable",
  charts: "stable",
  "progress-circle": "stable",
  tag: "preview",
  typography: "preview",
  "json-input": "preview",
  "time-picker": "preview",
  "sortable-list": "preview",
  "virtual-list": "preview",
  dnd: "preview",
}

export function getRegistryStatus(name: ComponentName): ComponentStatus {
  return registryStatus[name] ?? "preview"
}
