import {
  ClearableInput,
  ColorInput,
  DateInput,
  DateRangeInput,
  MaskedInput,
  MoneyInput,
  NumberInput,
  OtpInput,
  PasswordInput,
  PhoneInput,
  QuantityInput,
  QuantityStepper,
  Rating,
  RangeSlider,
  SearchInput,
  Slider,
  TagInput,
} from "@/components/inputs"
import {
  FormDateInput,
  FormDateRangeInput,
  FormInput,
  FormNumberInput,
  FormPasswordInput,
  FormPhoneInput,
  FormSearchInput,
} from "@/components/form"
import { Input } from "@/components/ui/input"

const InputFamily = {
  Root: Input,
  Clearable: ClearableInput,
  Search: SearchInput,
  Password: PasswordInput,
  Number: NumberInput,
  Date: DateInput,
  DateRange: DateRangeInput,
  Money: MoneyInput,
  Quantity: QuantityInput,
  Masked: MaskedInput,
  Phone: PhoneInput,
  Otp: OtpInput,
  Color: ColorInput,
  Tag: TagInput,
  Rating,
  Slider,
  RangeSlider,
  QuantityStepper,
  Form: {
    Input: FormInput,
    Search: FormSearchInput,
    Password: FormPasswordInput,
    Number: FormNumberInput,
    Phone: FormPhoneInput,
    Date: FormDateInput,
    DateRange: FormDateRangeInput,
  },
} as const

export { InputFamily }
