import type { ComponentFamilyName } from "@/families/catalog"

export type ComponentMemberMaturity = "canonical" | "member" | "transitional" | "advanced"

export type ComponentMemberMetadata = {
  component: string
  family: ComponentFamilyName
  section:
    | "primitives"
    | "presets"
    | "form-wrappers"
    | "wrappers"
    | "extensions"
    | "advanced"
    | "transitional"
  maturity: ComponentMemberMaturity
  summary: string
  useWhen: string
}

export const componentMemberMetadata: ComponentMemberMetadata[] = [
  {
    component: "Input",
    family: "InputFamily",
    section: "primitives",
    maturity: "canonical",
    summary: "Base text field primitive.",
    useWhen: "Use for standard single-line entry before reaching for formatted or decorated presets.",
  },
  {
    component: "ClearableInput",
    family: "InputFamily",
    section: "presets",
    maturity: "member",
    summary: "Input with built-in clear affordance.",
    useWhen: "Use for filters and quick-search surfaces where clearing the field should be one click.",
  },
  {
    component: "SearchInput",
    family: "InputFamily",
    section: "presets",
    maturity: "member",
    summary: "Search-flavored clearable input with icon defaults.",
    useWhen: "Use for search bars, table filters, and command-style query fields.",
  },
  {
    component: "PasswordInput",
    family: "InputFamily",
    section: "presets",
    maturity: "member",
    summary: "Password field with visibility toggle.",
    useWhen: "Use in auth and credential forms where reveal/hide improves accuracy.",
  },
  {
    component: "NumberInput",
    family: "InputFamily",
    section: "presets",
    maturity: "member",
    summary: "Text-backed numeric field with parsed value callbacks.",
    useWhen: "Use when you need browser-friendly number entry without relying on native spinner UX.",
  },
  {
    component: "MaskedInput",
    family: "InputFamily",
    section: "presets",
    maturity: "member",
    summary: "Formatting adapter around the base input.",
    useWhen: "Use when raw and displayed values differ, such as identifiers and custom entry masks.",
  },
  {
    component: "PhoneInput",
    family: "InputFamily",
    section: "presets",
    maturity: "member",
    summary: "Phone preset built on masking behavior.",
    useWhen: "Use for phone capture when you want readable formatting while storing digits.",
  },
  {
    component: "MoneyInput",
    family: "InputFamily",
    section: "presets",
    maturity: "member",
    summary: "Money-style field with prefix and suffix slots.",
    useWhen: "Use for finance and pricing fields that need currency context in the chrome.",
  },
  {
    component: "QuantityInput",
    family: "InputFamily",
    section: "presets",
    maturity: "member",
    summary: "Numeric entry with optional step controls.",
    useWhen: "Use for cart counts, stock edits, and compact quantity adjustments.",
  },
  {
    component: "OtpInput",
    family: "InputFamily",
    section: "presets",
    maturity: "member",
    summary: "Multi-cell one-time-code input.",
    useWhen: "Use for verification and short secure code flows that benefit from per-digit focus management.",
  },
  {
    component: "ColorInput",
    family: "InputFamily",
    section: "presets",
    maturity: "member",
    summary: "Color picker field.",
    useWhen: "Use when the browser-native color picker is enough for theme or label selection.",
  },
  {
    component: "DateInput",
    family: "InputFamily",
    section: "presets",
    maturity: "member",
    summary: "Native date field wrapper.",
    useWhen: "Use for lightweight date capture where a full calendar popover is unnecessary.",
  },
  {
    component: "DateRangeInput",
    family: "InputFamily",
    section: "presets",
    maturity: "member",
    summary: "Two-field date range input.",
    useWhen: "Use for admin filters and reports that only need from/to entry, not a visual calendar.",
  },
  {
    component: "FormInput",
    family: "InputFamily",
    section: "form-wrappers",
    maturity: "member",
    summary: "React Hook Form wrapper for the base input.",
    useWhen: "Use when you want Input behavior plus label, description, and error wiring from a shared form shell.",
  },
  {
    component: "FormSearchInput",
    family: "InputFamily",
    section: "form-wrappers",
    maturity: "member",
    summary: "RHF wrapper around SearchInput.",
    useWhen: "Use in filter or settings forms where search is part of submitted state.",
  },
  {
    component: "FormPasswordInput",
    family: "InputFamily",
    section: "form-wrappers",
    maturity: "member",
    summary: "RHF wrapper around PasswordInput.",
    useWhen: "Use in credential forms that need validation and shared field-shell behavior.",
  },
  {
    component: "FormNumberInput",
    family: "InputFamily",
    section: "form-wrappers",
    maturity: "member",
    summary: "RHF wrapper around NumberInput.",
    useWhen: "Use for parsed numeric form state with validation and descriptions.",
  },
  {
    component: "FormPhoneInput",
    family: "InputFamily",
    section: "form-wrappers",
    maturity: "member",
    summary: "RHF wrapper around PhoneInput.",
    useWhen: "Use for phone capture when the form layer should own validation and messaging.",
  },
  {
    component: "FormDateInput",
    family: "InputFamily",
    section: "form-wrappers",
    maturity: "member",
    summary: "RHF wrapper around DateInput.",
    useWhen: "Use for simple form dates that do not require a richer calendar surface.",
  },
  {
    component: "FormDateRangeInput",
    family: "InputFamily",
    section: "form-wrappers",
    maturity: "member",
    summary: "RHF wrapper around DateRangeInput.",
    useWhen: "Use for filter and reporting forms that submit a plain from/to range object.",
  },
  {
    component: "TagInput",
    family: "InputFamily",
    section: "advanced",
    maturity: "advanced",
    summary: "Multi-token freeform entry surface.",
    useWhen: "Use only when a basic input or select cannot represent repeated tokens cleanly.",
  },
  {
    component: "QuantityStepper",
    family: "InputFamily",
    section: "advanced",
    maturity: "advanced",
    summary: "Stepper-only quantity control.",
    useWhen: "Use for compact increment/decrement interactions where free typing should be avoided.",
  },

  {
    component: "Select",
    family: "SelectFamily",
    section: "primitives",
    maturity: "canonical",
    summary: "Base select primitive.",
    useWhen: "Use for standard single-select flows before introducing remote data or combobox behavior.",
  },
  {
    component: "SimpleSelect",
    family: "SelectFamily",
    section: "presets",
    maturity: "member",
    summary: "Opinionated simple option select.",
    useWhen: "Use for straightforward app settings and filter lists with static options.",
  },
  {
    component: "AsyncSelect",
    family: "SelectFamily",
    section: "presets",
    maturity: "member",
    summary: "Remote-search single select.",
    useWhen: "Use when options are loaded on demand from a server or large local source.",
  },
  {
    component: "AsyncMultiSelect",
    family: "SelectFamily",
    section: "presets",
    maturity: "member",
    summary: "Remote-search multi select.",
    useWhen: "Use when users need to pick many remote items and review selected tags inline.",
  },
  {
    component: "Combobox",
    family: "SelectFamily",
    section: "presets",
    maturity: "member",
    summary: "Searchable command-style select surface.",
    useWhen: "Use when fast keyboard filtering matters more than strict select semantics.",
  },
  {
    component: "FormSelect",
    family: "SelectFamily",
    section: "form-wrappers",
    maturity: "member",
    summary: "RHF wrapper for select usage.",
    useWhen: "Use when select state belongs to form submission and needs shell-driven messaging.",
  },
  {
    component: "FormAsyncSelect",
    family: "SelectFamily",
    section: "form-wrappers",
    maturity: "member",
    summary: "RHF wrapper for async select usage.",
    useWhen: "Use when remote single-select belongs to validated form state.",
  },

  {
    component: "Card",
    family: "CardFamily",
    section: "primitives",
    maturity: "canonical",
    summary: "Base card primitive.",
    useWhen: "Use for neutral content framing before adopting dashboard-specific presets.",
  },
  {
    component: "InfoCard",
    family: "CardFamily",
    section: "primitives",
    maturity: "canonical",
    summary: "Reusable composed information card.",
    useWhen: "Use for common metric and summary content where teams need a faster default than raw Card composition.",
  },
  {
    component: "StatCard",
    family: "CardFamily",
    section: "presets",
    maturity: "member",
    summary: "Compact stat display card.",
    useWhen: "Use for dashboard KPI rows and overview panels.",
  },
  {
    component: "StatisticCard",
    family: "CardFamily",
    section: "presets",
    maturity: "member",
    summary: "Structured statistic card.",
    useWhen: "Use when a metric needs trend, label, and support copy in one tile.",
  },
  {
    component: "EntityCard",
    family: "CardFamily",
    section: "presets",
    maturity: "member",
    summary: "Entity-oriented card surface.",
    useWhen: "Use for users, records, or business entities with compact metadata.",
  },
  {
    component: "FileCard",
    family: "CardFamily",
    section: "presets",
    maturity: "member",
    summary: "File preview card.",
    useWhen: "Use for uploads, attachments, and lightweight asset lists.",
  },
  {
    component: "SmartCard",
    family: "CardFamily",
    section: "transitional",
    maturity: "transitional",
    summary: "Older card alias kept for migration compatibility.",
    useWhen: "Use only when migrating existing surfaces; prefer Card or InfoCard for new usage.",
  },

  {
    component: "FormFieldShell",
    family: "FormFamily",
    section: "primitives",
    maturity: "canonical",
    summary: "Base shell for label, description, and validation copy.",
    useWhen: "Use as the common structure for any custom form control that needs consistent field framing.",
  },
  {
    component: "FormTextarea",
    family: "FormFamily",
    section: "wrappers",
    maturity: "member",
    summary: "RHF textarea wrapper.",
    useWhen: "Use for multi-line text in forms that need shared field-shell behavior.",
  },
  {
    component: "FormSwitch",
    family: "FormFamily",
    section: "wrappers",
    maturity: "member",
    summary: "RHF switch wrapper.",
    useWhen: "Use for boolean toggles tied to validation and descriptive copy.",
  },
  {
    component: "FormDatePicker",
    family: "FormFamily",
    section: "wrappers",
    maturity: "member",
    summary: "RHF wrapper around calendar date picker.",
    useWhen: "Use when the form needs a richer date picker than a native date input.",
  },
  {
    component: "FormDateRangePicker",
    family: "FormFamily",
    section: "wrappers",
    maturity: "member",
    summary: "RHF wrapper around calendar date range picker.",
    useWhen: "Use when a form needs a visual range-selection experience instead of plain from/to inputs.",
  },
  {
    component: "FormBuilder",
    family: "FormFamily",
    section: "advanced",
    maturity: "advanced",
    summary: "Schema-like abstraction over field wrappers.",
    useWhen: "Use only when repeated internal forms justify abstraction over direct wrapper composition.",
  },
  {
    component: "SmartFormShell",
    family: "FormFamily",
    section: "advanced",
    maturity: "transitional",
    summary: "Older shell abstraction kept during migration.",
    useWhen: "Use only for migration or legacy screens; prefer FormFieldShell and explicit wrappers for new work.",
  },

  {
    component: "DataTable",
    family: "DataTableFamily",
    section: "primitives",
    maturity: "canonical",
    summary: "Canonical tabular data surface.",
    useWhen: "Use when rows, sorting, selection, and pagination belong in one reusable grid.",
  },
  {
    component: "DataTableToolbar",
    family: "DataTableFamily",
    section: "extensions",
    maturity: "member",
    summary: "Toolbar scaffold for table actions and filters.",
    useWhen: "Use when the table needs a structured top bar instead of ad-hoc controls.",
  },
  {
    component: "DataTablePagination",
    family: "DataTableFamily",
    section: "extensions",
    maturity: "member",
    summary: "Pagination control for the data table.",
    useWhen: "Use when pagination UI should remain visually aligned with the table system.",
  },
  {
    component: "DataTableColumnVisibilityMenu",
    family: "DataTableFamily",
    section: "extensions",
    maturity: "member",
    summary: "Hide/show columns control.",
    useWhen: "Use when dense tables need user-level column personalization.",
  },
  {
    component: "DataTableSortableHeader",
    family: "DataTableFamily",
    section: "extensions",
    maturity: "member",
    summary: "Sortable header helper.",
    useWhen: "Use when a column header needs consistent sort affordance and state rendering.",
  },
  {
    component: "DataTableRowActions",
    family: "DataTableFamily",
    section: "extensions",
    maturity: "member",
    summary: "Row-level actions surface.",
    useWhen: "Use when each row needs contextual actions without custom menu plumbing.",
  },
  {
    component: "DataTableBulkActions",
    family: "DataTableFamily",
    section: "extensions",
    maturity: "member",
    summary: "Bulk selection action surface.",
    useWhen: "Use when multi-row operations should appear only after selection.",
  },
  {
    component: "DataTableViewPresets",
    family: "DataTableFamily",
    section: "extensions",
    maturity: "member",
    summary: "Preset view controls for table states.",
    useWhen: "Use when users need quick switching between saved or opinionated table views.",
  },
  {
    component: "createDataTableSelectColumn",
    family: "DataTableFamily",
    section: "extensions",
    maturity: "member",
    summary: "Selection column factory.",
    useWhen: "Use when you want standard row-selection behavior without rewriting the column definition.",
  },
  {
    component: "createDataTableActionsColumn",
    family: "DataTableFamily",
    section: "extensions",
    maturity: "member",
    summary: "Actions column factory.",
    useWhen: "Use when row action menus should follow the shared table contract.",
  },
  {
    component: "TableExportMenu",
    family: "DataTableFamily",
    section: "advanced",
    maturity: "advanced",
    summary: "Export helpers for tables.",
    useWhen: "Use only after the core table experience is already clear and export is truly required.",
  },
  {
    component: "TableImportButton",
    family: "DataTableFamily",
    section: "advanced",
    maturity: "advanced",
    summary: "Import trigger tied to table workflows.",
    useWhen: "Use only when import belongs directly beside a data table management flow.",
  },
] as const
