import type { ComponentFamilyName } from "@/families/catalog"

export type FamilyMigrationStatus =
  | "canonical"
  | "family-member"
  | "family-member helper"
  | "canonical composed member"
  | "transitional"
  | "advanced"

export type FamilyMigrationEntry = {
  component: string
  family: ComponentFamilyName
  member?: string
  status: FamilyMigrationStatus
  notes?: string
}

export const componentFamilyMigrationMap: FamilyMigrationEntry[] = [
  { component: "Input", family: "InputFamily", member: "Root", status: "canonical" },
  { component: "Textarea", family: "InputFamily", member: "Textarea", status: "canonical composed member" },
  { component: "FormInput", family: "InputFamily", member: "FormInput", status: "family-member helper" },
  { component: "ClearableInput", family: "InputFamily", member: "Clearable", status: "transitional" },
  { component: "SearchInput", family: "InputFamily", member: "Search", status: "transitional" },
  { component: "PasswordInput", family: "InputFamily", member: "Password", status: "family-member" },
  { component: "NumberInput", family: "InputFamily", member: "Number", status: "family-member" },
  { component: "Slider", family: "InputFamily", member: "Slider", status: "advanced" },
  { component: "RangeSlider", family: "InputFamily", member: "RangeSlider", status: "advanced" },
  { component: "Rating", family: "InputFamily", member: "Rating", status: "advanced" },
  { component: "DateInput", family: "InputFamily", member: "Date", status: "family-member" },
  { component: "DateRangeInput", family: "InputFamily", member: "DateRange", status: "family-member" },
  { component: "MoneyInput", family: "InputFamily", member: "Money", status: "family-member" },
  { component: "QuantityInput", family: "InputFamily", member: "Quantity", status: "transitional" },
  { component: "MaskedInput", family: "InputFamily", member: "Masked", status: "transitional" },
  { component: "PhoneInput", family: "InputFamily", member: "Phone", status: "family-member" },
  { component: "OtpInput", family: "InputFamily", member: "Otp", status: "advanced" },
  { component: "ColorInput", family: "InputFamily", member: "Color", status: "advanced" },
  { component: "TagInput", family: "InputFamily", member: "Tag", status: "advanced" },
  { component: "QuantityStepper", family: "InputFamily", member: "QuantityStepper", status: "advanced" },

  { component: "Select", family: "SelectFamily", member: "Root", status: "canonical" },
  { component: "SimpleSelect", family: "SelectFamily", member: "Simple", status: "transitional" },
  { component: "AsyncSelect", family: "SelectFamily", member: "Async", status: "family-member" },
  { component: "AsyncMultiSelect", family: "SelectFamily", member: "AsyncMulti", status: "family-member" },
  { component: "Combobox", family: "SelectFamily", member: "Combobox", status: "family-member" },
  { component: "FormSelect", family: "SelectFamily", member: "Form.Select", status: "family-member" },
  { component: "FormAsyncSelect", family: "SelectFamily", member: "Form.Async", status: "transitional" },

  { component: "Card", family: "CardFamily", member: "Root", status: "canonical" },
  { component: "InfoCard", family: "CardFamily", member: "Info", status: "canonical composed member" },
  { component: "SmartCard", family: "CardFamily", member: "Info", status: "transitional", notes: "Prefer InfoCard or CardFamily.Info in docs and new usage." },
  { component: "StatCard", family: "CardFamily", member: "Stat", status: "transitional", notes: "Prefer StatisticCard or InfoCard for new usage." },
  { component: "StatisticCard", family: "CardFamily", member: "Statistic", status: "family-member" },
  { component: "EntityCard", family: "CardFamily", member: "Entity", status: "family-member" },
  { component: "FileCard", family: "CardFamily", member: "File", status: "family-member" },

  { component: "Badge", family: "BadgeFamily", member: "Root", status: "canonical" },

  { component: "Dialog", family: "OverlayFamily", member: "Dialog", status: "canonical" },
  { component: "Popover", family: "OverlayFamily", member: "Popover", status: "canonical" },
  { component: "DropdownMenu", family: "OverlayFamily", member: "DropdownMenu", status: "canonical" },
  { component: "Tooltip", family: "OverlayFamily", member: "Tooltip", status: "family-member" },
  { component: "HoverCard", family: "OverlayFamily", member: "HoverCard", status: "family-member" },
  { component: "RightClickMenu", family: "OverlayFamily", member: "RightClickMenu", status: "transitional" },
  { component: "AlertDialog", family: "OverlayFamily", member: "AlertDialog", status: "transitional" },
  { component: "ConfirmDialog", family: "OverlayFamily", member: "ConfirmDialog", status: "family-member" },
  { component: "ModalShell", family: "OverlayFamily", member: "ModalShell", status: "transitional" },
  { component: "SheetShell", family: "OverlayFamily", member: "SheetShell", status: "family-member" },
  { component: "Drawer", family: "OverlayFamily", member: "Drawer", status: "transitional" },
  { component: "DialogActions", family: "OverlayFamily", member: "DialogActions", status: "transitional" },

  { component: "FormFieldShell", family: "FormFamily", member: "Field", status: "canonical" },
  { component: "FormInput", family: "FormFamily", member: "Input", status: "family-member" },
  { component: "FormTextarea", family: "FormFamily", member: "Textarea", status: "family-member" },
  { component: "FormSelect", family: "FormFamily", member: "Select", status: "family-member" },
  { component: "FormAsyncSelect", family: "FormFamily", member: "AsyncSelect", status: "family-member" },
  { component: "FormSwitch", family: "FormFamily", member: "Switch", status: "family-member" },
  { component: "FormSearchInput", family: "FormFamily", member: "Search", status: "transitional" },
  { component: "FormPasswordInput", family: "FormFamily", member: "Password", status: "transitional" },
  { component: "FormNumberInput", family: "FormFamily", member: "Number", status: "transitional" },
  { component: "FormPhoneInput", family: "FormFamily", member: "Phone", status: "transitional" },
  { component: "FormDateInput", family: "FormFamily", member: "Date", status: "transitional" },
  { component: "FormDateRangeInput", family: "FormFamily", member: "DateRange", status: "transitional" },
  { component: "FormDatePicker", family: "FormFamily", member: "DatePicker", status: "family-member" },
  { component: "FormDateRangePicker", family: "FormFamily", member: "DateRangePicker", status: "family-member" },
  { component: "FormBuilder", family: "FormFamily", member: "Builder", status: "advanced" },

  { component: "DataTable", family: "DataTableFamily", member: "Root", status: "canonical" },
  { component: "DataTableToolbar", family: "DataTableFamily", member: "Toolbar", status: "family-member" },
  { component: "DataTablePagination", family: "DataTableFamily", member: "Pagination", status: "family-member" },
  { component: "DataTableColumnVisibilityMenu", family: "DataTableFamily", member: "ColumnVisibilityMenu", status: "family-member" },
  { component: "DataTableSortableHeader", family: "DataTableFamily", member: "SortableHeader", status: "family-member" },
  { component: "DataTableRowActions", family: "DataTableFamily", member: "RowActions", status: "family-member" },
  { component: "DataTableBulkActions", family: "DataTableFamily", member: "BulkActions", status: "family-member" },
  { component: "DataTableViewPresets", family: "DataTableFamily", member: "ViewPresets", status: "family-member" },
  { component: "createDataTableSelectColumn", family: "DataTableFamily", member: "createSelectColumn", status: "family-member helper" },
  { component: "createDataTableActionsColumn", family: "DataTableFamily", member: "createActionsColumn", status: "family-member helper" },
  { component: "TableExportMenu", family: "DataTableFamily", member: "ExportMenu", status: "advanced" },
  { component: "TableImportButton", family: "DataTableFamily", member: "ImportButton", status: "advanced" },
  { component: "InlineEditable", family: "InputFamily", member: "InlineEditable", status: "advanced" },
  { component: "TrendCard", family: "CardFamily", member: "Trend", status: "family-member" },
  { component: "ComparisonCard", family: "CardFamily", member: "Comparison", status: "family-member" },
  { component: "DeltaBadge", family: "BadgeFamily", member: "Delta", status: "family-member" },
  { component: "RepeaterField", family: "FormFamily", member: "Repeater", status: "family-member" },
  { component: "Button", family: "ActionFamily", member: "Root", status: "canonical" },
  { component: "ActionMenu", family: "ActionFamily", member: "Menu", status: "family-member" },
  { component: "CopyButton", family: "ActionFamily", member: "CopyButton", status: "family-member" },
  { component: "ButtonGroup", family: "ActionFamily", member: "Group", status: "transitional" },
  { component: "CopyField", family: "ActionFamily", member: "CopyField", status: "transitional" },
  { component: "QuickActionGrid", family: "ActionFamily", member: "QuickActionGrid", status: "transitional" },

  { component: "Alert", family: "FeedbackFamily", member: "Alert", status: "canonical" },
  { component: "EmptyState", family: "FeedbackFamily", member: "EmptyState", status: "canonical" },
  { component: "LoadingState", family: "FeedbackFamily", member: "LoadingState", status: "canonical" },
  { component: "Progress", family: "FeedbackFamily", member: "Progress", status: "canonical" },
  { component: "ToastProvider", family: "FeedbackFamily", member: "ToastProvider", status: "canonical" },
  { component: "InlineState", family: "FeedbackFamily", member: "InlineState", status: "family-member" },
  { component: "LoadingOverlay", family: "FeedbackFamily", member: "LoadingOverlay", status: "family-member" },
  { component: "Spinner", family: "FeedbackFamily", member: "Spinner", status: "family-member" },
  { component: "Skeleton", family: "FeedbackFamily", member: "Skeleton", status: "family-member" },
  { component: "useToast", family: "FeedbackFamily", member: "useToast", status: "advanced" },

  { component: "BarChart", family: "ChartFamily", member: "BarChart", status: "canonical" },
  { component: "LineChart", family: "ChartFamily", member: "LineChart", status: "canonical" },
  { component: "DonutChart", family: "ChartFamily", member: "DonutChart", status: "canonical" },
  { component: "MetricGrid", family: "ChartFamily", member: "MetricGrid", status: "family-member" },
  { component: "ChartFrame", family: "ChartFamily", member: "ChartFrame", status: "family-member" },
  { component: "ChartLegend", family: "ChartFamily", member: "ChartLegend", status: "family-member" },
  { component: "Sparkline", family: "ChartFamily", member: "Sparkline", status: "family-member" },
  { component: "MetricTrend", family: "ChartFamily", member: "MetricTrend", status: "family-member" },
  { component: "Statistic", family: "ChartFamily", member: "Statistic", status: "family-member" },
  { component: "StatisticGrid", family: "ChartFamily", member: "StatisticGrid", status: "family-member" },
  { component: "StatisticCard", family: "ChartFamily", member: "StatisticCard", status: "family-member" },

  { component: "Sidebar", family: "NavigationFamily", member: "Sidebar", status: "canonical" },
  { component: "PageContainer", family: "NavigationFamily", member: "PageContainer", status: "canonical" },
  { component: "Tabs", family: "NavigationFamily", member: "Tabs", status: "canonical" },
  { component: "Pagination", family: "NavigationFamily", member: "Pagination", status: "canonical" },
  { component: "Breadcrumbs", family: "NavigationFamily", member: "Breadcrumbs", status: "canonical" },
  { component: "Wizard", family: "NavigationFamily", member: "Wizard", status: "canonical" },
  { component: "Section", family: "NavigationFamily", member: "Section", status: "transitional" },
  { component: "AnchorNav", family: "NavigationFamily", member: "AnchorNav", status: "transitional" },
  { component: "Stepper", family: "NavigationFamily", member: "Stepper", status: "transitional" },
  { component: "StepperTabs", family: "NavigationFamily", member: "StepperTabs", status: "transitional" },
  { component: "SegmentedControl", family: "NavigationFamily", member: "SegmentedControl", status: "transitional" },

  { component: "FileUpload", family: "UploadFamily", member: "FileUpload", status: "canonical" },
  { component: "ImageUpload", family: "UploadFamily", member: "ImageUpload", status: "canonical composed member" },

  { component: "Checkbox", family: "PrimitiveFamily", member: "Checkbox", status: "canonical" },
  { component: "RadioGroup", family: "PrimitiveFamily", member: "RadioGroup", status: "canonical" },
  { component: "Switch", family: "PrimitiveFamily", member: "Switch", status: "canonical" },
  { component: "Table", family: "PrimitiveFamily", member: "Table", status: "canonical" },
  { component: "Accordion", family: "PrimitiveFamily", member: "Accordion", status: "canonical" },
  { component: "Collapse", family: "PrimitiveFamily", member: "Collapse", status: "transitional" },
  { component: "Calendar", family: "PrimitiveFamily", member: "Calendar", status: "transitional" },
  { component: "Divider", family: "PrimitiveFamily", member: "Divider", status: "transitional" },
  { component: "Kbd", family: "PrimitiveFamily", member: "Kbd", status: "transitional" },
  { component: "ScrollBox", family: "PrimitiveFamily", member: "ScrollBox", status: "transitional" },
] as const
