export const additionalPublicFamilies = [
  {
    family: "ActionFamily",
    label: "Actions",
    description: "Primary action surface led by Button, then expanded with menus, copy flows, and grouped actions.",
    canonical: ["Button"],
    members: ["ActionMenu", "CopyButton"],
    transitional: ["ButtonGroup", "CopyField", "QuickActionGrid"],
  },
  {
    family: "FeedbackFamily",
    label: "Feedback",
    description: "Status, loading, and notification surfaces grouped under one product feedback mental model.",
    canonical: ["Alert", "EmptyState", "LoadingState", "ToastProvider"],
    members: ["InlineState", "LoadingOverlay", "Spinner", "Skeleton"],
    advanced: ["useToast"],
  },
  {
    family: "ChartFamily",
    label: "Charts",
    description: "Dashboard chart and metric surfaces with one clear chart-led public route.",
    canonical: ["BarChart", "LineChart", "DonutChart"],
    members: ["MetricGrid", "ChartFrame", "ChartLegend", "Sparkline", "MetricTrend", "Statistic", "StatisticGrid", "StatisticCard"],
  },
  {
    family: "NavigationFamily",
    label: "Navigation",
    description: "Navigation, page framing, and guided-flow surfaces grouped around one layout-first route.",
    canonical: ["Sidebar", "PageContainer", "Tabs", "Pagination", "Breadcrumbs", "Wizard"],
    members: [],
    transitional: ["Section", "AnchorNav", "Stepper", "StepperTabs", "SegmentedControl"],
  },
  {
    family: "UploadFamily",
    label: "Upload",
    description: "File and image upload surfaces with source-ready product behavior.",
    canonical: ["FileUpload", "ImageUpload"],
    members: [],
  },
  {
    family: "PrimitiveFamily",
    label: "Primitives",
    description: "Form and content primitives that support higher-level product surfaces without crowding the catalog.",
    canonical: ["Checkbox", "RadioGroup", "Switch", "Table", "Accordion"],
    members: [],
    transitional: ["Collapse", "Calendar", "Divider", "Kbd", "ScrollBox"],
  },
] as const

export const additionalDocsGroups = [
  {
    group: "Button",
    family: "ActionFamily",
    slug: "button",
    label: "Button",
    primaryComponent: "Button",
    description: "Button-first action route with menu, copy, and grouped-action helpers introduced only after the main trigger is clear.",
    sections: [
      {
        id: "core-actions",
        label: "Core actions",
        description: "Start from the primary action trigger, then expand into menu and copy patterns only when the flow needs them.",
        components: ["Button", "ActionMenu", "CopyButton"],
      },
      {
        id: "secondary-patterns",
        label: "Secondary patterns",
        description: "Grouped and embedded action helpers should stay secondary to the core action surface.",
        components: ["ButtonGroup", "CopyField", "QuickActionGrid"],
      },
    ],
  },
  {
    group: "Alert",
    family: "FeedbackFamily",
    slug: "alert",
    label: "Alert",
    primaryComponent: "Alert",
    description: "Feedback route for product status, empty, loading, progress, and notifications.",
    sections: [
      {
        id: "core-feedback",
        label: "Core feedback",
        description: "These are the product feedback surfaces teams should reach for first.",
        components: ["Alert", "EmptyState", "LoadingState", "ToastProvider"],
      },
      {
        id: "secondary-feedback",
        label: "Secondary feedback",
        description: "Loading helpers and inline state affordances should stay behind the core feedback model.",
        components: ["InlineState", "LoadingOverlay", "Spinner", "Skeleton", "useToast"],
      },
    ],
  },
  {
    group: "BarChart",
    family: "ChartFamily",
    slug: "bar-chart",
    label: "Bar Chart",
    primaryComponent: "BarChart",
    description: "Chart-first route for dashboard visuals and metric companions.",
    sections: [
      {
        id: "core-charts",
        label: "Core charts",
        description: "Lead with the chart surfaces that carry direct dashboard value.",
        components: ["BarChart", "LineChart", "DonutChart", "MetricGrid"],
      },
      {
        id: "chart-helpers",
        label: "Chart helpers",
        description: "Frames, legends, and metric add-ons stay as secondary pieces around the chart route.",
        components: ["ChartFrame", "ChartLegend", "Sparkline", "MetricTrend", "Statistic", "StatisticGrid", "StatisticCard"],
      },
    ],
  },
  {
    group: "Sidebar",
    family: "NavigationFamily",
    slug: "sidebar",
    label: "Sidebar",
    primaryComponent: "Sidebar",
    description: "Navigation and layout route with page framing, tabs, pagination, and guided flows grouped together.",
    sections: [
      {
        id: "core-navigation",
        label: "Core navigation",
        description: "Start from the main navigational and framing surfaces.",
        components: ["Sidebar", "PageContainer", "Tabs", "Pagination", "Breadcrumbs", "Wizard"],
      },
      {
        id: "secondary-navigation",
        label: "Secondary navigation",
        description: "Structural helpers and guided-flow variants should stay behind the main navigation route.",
        components: ["Section", "AnchorNav", "Stepper", "StepperTabs", "SegmentedControl"],
      },
    ],
  },
  {
    group: "FileUpload",
    family: "UploadFamily",
    slug: "file-upload",
    label: "File Upload",
    primaryComponent: "FileUpload",
    description: "Upload route that starts from the generic file workflow and then expands into image-specific behavior.",
    sections: [
      {
        id: "upload-core",
        label: "Upload core",
        description: "Generic file and image upload flows with direct product behavior.",
        components: ["FileUpload", "ImageUpload"],
      },
    ],
  },
  {
    group: "Checkbox",
    family: "PrimitiveFamily",
    slug: "checkbox",
    label: "Checkbox",
    primaryComponent: "Checkbox",
    description: "Primitive route for selection, tables, and supporting building blocks that should not dominate the main catalog.",
    sections: [
      {
        id: "core-primitives",
        label: "Core primitives",
        description: "Lead with the selection and content primitives used most often in real product screens.",
        components: ["Checkbox", "RadioGroup", "Switch", "Table", "Accordion"],
      },
      {
        id: "supporting-primitives",
        label: "Supporting primitives",
        description: "Supporting content and layout primitives should stay secondary to the core controls.",
        components: ["Collapse", "Calendar", "Divider", "Kbd", "ScrollBox"],
      },
    ],
  },
] as const
