import path from "path"
import fs from "fs-extra"
import prompts from "prompts"
import { logger } from "../utils/logger"
import { detectPackageManager } from "../utils/detect-package-manager"
import { installPackages } from "../utils/install-packages"
import { upsertThemeCss } from "../utils/upsert-theme-css"
import { getCliNpxCommand, LIBRARY_PACKAGE_NAME } from "../utils/cli-metadata"

const baseDependencies = [
  LIBRARY_PACKAGE_NAME,
  "@base-ui/react",
  "@fontsource-variable/geist",
  "clsx",
  "tailwind-merge",
  "class-variance-authority",
  "lucide-react",
  "tw-animate-css",
  "@tanstack/react-table",
  "react-hook-form",
]

const templateTailwindDependencies: Record<InitTemplate, string[]> = {
  vite: ["tailwindcss", "@tailwindcss/vite"],
  next: ["tailwindcss", "@tailwindcss/postcss"],
}

type InitTemplate = "vite" | "next"

type InitCommandOptions = {
  template?: string
  skipInstall?: boolean
  defaults?: boolean
}

type InitResponse = {
  installDeps: boolean
  installTailwindDeps: boolean
  alias: string
  componentsPath: string
  uiPath: string
  hooksPath: string
  utilsPath: string
  globalCssPath: string
  writeThemeCss: boolean
}

const placeholderBarrel = `// Generated by azamat-ui-kit init.\n// Components added with the CLI will appear under this folder.\n`

function parseJsonc(content: string) {
  const withoutBlockComments = content.replace(/\/\*[\s\S]*?\*\//g, "")
  const withoutLineComments = withoutBlockComments.replace(/^\s*\/\/.*$/gm, "")
  const withoutTrailingCommas = withoutLineComments.replace(/,\s*([}\]])/g, "$1")
  return JSON.parse(withoutTrailingCommas) as Record<string, unknown>
}

function getAliasTargetPath(template: InitTemplate, componentsPath: string, hooksPath: string, utilsPath: string) {
  if (template === "vite") {
    const candidatePaths = [componentsPath, hooksPath, utilsPath]
      .map((value) => value.replaceAll("\\", "/"))

    const sourceLike = candidatePaths.filter((value) => value.startsWith("src/"))
    if (sourceLike.length === candidatePaths.length) return "./src/*"
  }

  return "./*"
}

async function ensureTsconfigAlias({
  cwd,
  template,
  alias,
  componentsPath,
  hooksPath,
  utilsPath,
}: {
  cwd: string
  template: InitTemplate
  alias: string
  componentsPath: string
  hooksPath: string
  utilsPath: string
}) {
  const tsconfigPath = path.join(cwd, template === "vite" ? "tsconfig.app.json" : "tsconfig.json")

  if (!fs.existsSync(tsconfigPath)) return

  const tsconfig = parseJsonc(await fs.readFile(tsconfigPath, "utf8")) as {
    compilerOptions?: Record<string, unknown>
  }

  tsconfig.compilerOptions ??= {}
  tsconfig.compilerOptions.ignoreDeprecations ??= "6.0"
  tsconfig.compilerOptions.baseUrl = "."

  const paths = ((tsconfig.compilerOptions.paths ?? {}) as Record<string, string[]>)
  paths[`${alias}/*`] = [getAliasTargetPath(template, componentsPath, hooksPath, utilsPath)]
  tsconfig.compilerOptions.paths = paths

  await fs.writeJson(tsconfigPath, tsconfig, { spaces: 2 })
}

async function ensureViteAlias({
  cwd,
  alias,
}: {
  cwd: string
  alias: string
}) {
  const viteConfigPath = path.join(cwd, "vite.config.ts")
  if (!fs.existsSync(viteConfigPath)) return

  const currentContent = await fs.readFile(viteConfigPath, "utf8")
  const importLine = `import path from 'node:path'`
  const resolveBlock = `  resolve: {\n    alias: {\n      '${alias}': path.resolve(process.cwd(), 'src'),\n    },\n  },`

  let nextContent = currentContent

  if (!nextContent.includes(importLine)) {
    nextContent = `${importLine}\n${nextContent}`
  }

  if (!nextContent.includes("resolve: {") && nextContent.includes("export default defineConfig({")) {
    nextContent = nextContent.replace("export default defineConfig({", `export default defineConfig({\n${resolveBlock}`)
  }

  if (!nextContent.includes(`'${alias}': path.resolve(process.cwd(), 'src')`)) {
    await fs.writeFile(viteConfigPath, nextContent)
  } else if (nextContent !== currentContent) {
    await fs.writeFile(viteConfigPath, nextContent)
  }
}

const templateDefaults: Record<InitTemplate, Omit<InitResponse, "installDeps" | "writeThemeCss">> = {
  vite: {
    alias: "@",
    componentsPath: "src/components",
    uiPath: "src/components/ui",
    hooksPath: "src/hooks",
    utilsPath: "src/lib/utils.ts",
    globalCssPath: "src/index.css",
  },
  next: {
    alias: "@",
    componentsPath: "components",
    uiPath: "components/ui",
    hooksPath: "hooks",
    utilsPath: "lib/utils.ts",
    globalCssPath: "app/globals.css",
  },
}

function resolveTemplate(value?: string): InitTemplate {
  if (value === "next" || value === "vite") return value

  logger.warn(`Unknown template '${value}'. Falling back to vite defaults.`)
  return "vite"
}

function getInstalledPackages(cwd: string) {
  const packageJsonPath = path.join(cwd, "package.json")
  const packageJson = fs.readJsonSync(packageJsonPath) as {
    dependencies?: Record<string, string>
    devDependencies?: Record<string, string>
  }

  return new Set([
    ...Object.keys(packageJson.dependencies ?? {}),
    ...Object.keys(packageJson.devDependencies ?? {}),
  ])
}

export async function initCommand(options: InitCommandOptions = {}) {
  const cwd = process.cwd()
  const packageJsonPath = path.join(cwd, "package.json")

  if (!fs.existsSync(packageJsonPath)) {
    logger.error("package.json topilmadi / not found. Commandni React, Vite yoki Next project ichida ishlating.")
    process.exit(1)
  }

  const template = resolveTemplate(options.template)
  const defaults = templateDefaults[template]
  const installedPackages = getInstalledPackages(cwd)
  const missingTailwindDependencies = templateTailwindDependencies[template].filter((pkg) => !installedPackages.has(pkg))

  const response = options.defaults
    ? ({
        installDeps: !options.skipInstall,
        installTailwindDeps: missingTailwindDependencies.length > 0,
        alias: defaults.alias,
        componentsPath: defaults.componentsPath,
        uiPath: defaults.uiPath,
        hooksPath: defaults.hooksPath,
        utilsPath: defaults.utilsPath,
        globalCssPath: defaults.globalCssPath,
        writeThemeCss: true,
      } satisfies InitResponse)
    : ((await prompts([
    {
      type: "confirm",
      name: "installDeps",
      message: "Asosiy dependencylarni o‘rnataymi? / Install base dependencies?",
      initial: !options.skipInstall,
    },
    {
      type: missingTailwindDependencies.length > 0 ? "confirm" : null,
      name: "installTailwindDeps",
      message: `Tailwind paketlari topilmadi (${missingTailwindDependencies.join(", ")}). O‘rnataymi? / Install Tailwind packages?`,
      initial: true,
    },
    {
      type: "text",
      name: "alias",
      message: "Path alias qanday? / Path alias?",
      initial: defaults.alias,
    },
    {
      type: "text",
      name: "componentsPath",
      message: "Component root qayerda? / Component root?",
      initial: defaults.componentsPath,
    },
    {
      type: "text",
      name: "uiPath",
      message: "UI primitives qayerga yozilsin? / UI primitives path?",
      initial: defaults.uiPath,
    },
    {
      type: "text",
      name: "hooksPath",
      message: "Hooks qayerga yozilsin? / Hooks path?",
      initial: defaults.hooksPath,
    },
    {
      type: "text",
      name: "utilsPath",
      message: "utils.ts qayerga yozilsin? / utils.ts path?",
      initial: defaults.utilsPath,
    },
    {
      type: "text",
      name: "globalCssPath",
      message: "Theme tokenlar qaysi global CSS faylga yozilsin? / Global CSS path?",
      initial: defaults.globalCssPath,
    },
    {
      type: "confirm",
      name: "writeThemeCss",
      message: "Dark/light theme tokenlarni global CSS faylga yozaymi? / Write theme tokens?",
      initial: true,
    },
  ])) as InitResponse)

  const packageManager = detectPackageManager(cwd)

  logger.info(`Package manager: ${packageManager}`)

  if (!options.skipInstall && response.installDeps) {
    await installPackages({
      cwd,
      packageManager,
      packages: baseDependencies,
    })
  }

  if (!options.skipInstall && missingTailwindDependencies.length > 0 && response.installTailwindDeps) {
    await installPackages({
      cwd,
      packageManager,
      packages: missingTailwindDependencies,
      dev: true,
    })
  }

  const utilsPath = response.utilsPath || defaults.utilsPath
  const componentsPath = response.componentsPath || defaults.componentsPath
  const uiPath = response.uiPath || defaults.uiPath
  const hooksPath = response.hooksPath || defaults.hooksPath
  const globalCssPath = response.globalCssPath || defaults.globalCssPath

  const config = {
    style: "default",
    alias: response.alias || defaults.alias,
    componentsPath,
    utilsPath,
    cssPath: globalCssPath,
    globalCssPath,
    paths: {
      components: componentsPath,
      ui: uiPath,
      hooks: hooksPath,
      lib: path.dirname(utilsPath),
    },
  }

  await fs.writeJson(path.join(cwd, "azamat-ui.json"), config, {
    spaces: 2,
  })

  const utilsFullPath = path.join(cwd, utilsPath)
  const componentsRootPath = path.join(cwd, componentsPath)
  const uiRootPath = path.join(cwd, uiPath)
  const hooksRootPath = path.join(cwd, hooksPath)
  await fs.ensureDir(path.dirname(utilsFullPath))
  await fs.ensureDir(componentsRootPath)
  await fs.ensureDir(uiRootPath)
  await fs.ensureDir(hooksRootPath)

  const componentBarrels = [
    path.join(componentsRootPath, "index.ts"),
    path.join(uiRootPath, "index.ts"),
    path.join(hooksRootPath, "index.ts"),
  ]

  for (const barrelPath of componentBarrels) {
    if (!fs.existsSync(barrelPath)) {
      await fs.writeFile(barrelPath, placeholderBarrel)
    }
  }

  if (!fs.existsSync(utilsFullPath)) {
    await fs.writeFile(
      utilsFullPath,
      `import { clsx, type ClassValue } from "clsx"
import { twMerge } from "tailwind-merge"

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}
`
    )
  }

  await ensureTsconfigAlias({
    cwd,
    template,
    alias: config.alias,
    componentsPath,
    hooksPath,
    utilsPath,
  })

  if (template === "vite") {
    await ensureViteAlias({
      cwd,
      alias: config.alias,
    })
  }

  if (response.writeThemeCss && globalCssPath) {
    const cssTarget = await upsertThemeCss({
      cwd,
      cssPath: globalCssPath,
    })

    logger.success(`Theme CSS yozildi / written: ${cssTarget}`)
  }

  logger.success("Azamat UI Kit init qilindi / initialized.")
  logger.info(`Component source root: ${componentsPath}`)
  logger.info(`UI primitives path: ${uiPath}`)
  logger.info(`Hooks path: ${hooksPath}`)
  logger.info("Componentlarni ko‘rish / list components:")
  logger.info(getCliNpxCommand("list"))
  logger.info("Component qo‘shish / add components:")
  logger.info(getCliNpxCommand("add button input data-table"))
  if (missingTailwindDependencies.length > 0 && !response.installTailwindDeps) {
    logger.warn(`Tailwind paketlari hali o‘rnatilmadi: ${missingTailwindDependencies.join(", ")}`)
  }
  logger.info("Theme CSS ni yangilash / update theme CSS:")
  logger.info(getCliNpxCommand("theme"))
}
