import path from "path"
import fs from "fs-extra"
import prompts from "prompts"
import { logger } from "../utils/logger"
import { detectPackageManager } from "../utils/detect-package-manager"
import { installPackages } from "../utils/install-packages"
import { upsertThemeCss } from "../utils/upsert-theme-css"
import { getCliNpxCommand } from "../utils/cli-metadata"
import { addCommand } from "./add"

const baseDependencies = [
  "@fontsource-variable/geist",
  "clsx",
  "tailwind-merge",
  "tw-animate-css",
]

const templateTailwindDependencies: Record<InitTemplate, string[]> = {
  vite: ["tailwindcss", "@tailwindcss/vite"],
  next: ["tailwindcss", "@tailwindcss/postcss"],
}

type InitTemplate = "vite" | "next"

type InitCommandOptions = {
  template?: string
  skipInstall?: boolean
  defaults?: boolean
  showcase?: boolean
}

type TembroConfig = {
  style?: string
  alias?: string
  componentsPath?: string
  utilsPath?: string
  cssPath?: string
  globalCssPath?: string
  paths?: {
    components?: string
    ui?: string
    hooks?: string
    lib?: string
  }
}

type InitResponse = {
  installDeps: boolean
  installTailwindDeps: boolean
  alias: string
  componentsPath: string
  uiPath: string
  hooksPath: string
  utilsPath: string
  globalCssPath: string
  writeThemeCss: boolean
}

const placeholderBarrel = `// Generated by tembro init.\n// Components added with the CLI will appear under this folder.\n`

function parseJsonc(content: string) {
  try {
    return JSON.parse(content) as Record<string, unknown>
  } catch {
    // Fall back to a small JSONC cleanup for config files that actually contain comments.
  }

  const withoutBlockComments = content.replace(/\/\*[\s\S]*?\*\//g, "")
  const withoutLineComments = withoutBlockComments.replace(/^\s*\/\/.*$/gm, "")
  const withoutTrailingCommas = withoutLineComments.replace(/,\s*([}\]])/g, "$1")
  return JSON.parse(withoutTrailingCommas) as Record<string, unknown>
}

function getAliasTargetPath(template: InitTemplate, componentsPath: string, hooksPath: string, utilsPath: string) {
  const candidatePaths = [componentsPath, hooksPath, utilsPath]
    .map((value) => value.replaceAll("\\", "/"))

  const sourceLike = candidatePaths.filter((value) => value.startsWith("src/"))
  if (sourceLike.length === candidatePaths.length) return "./src/*"

  return "./*"
}

async function ensureTsconfigAlias({
  cwd,
  template,
  alias,
  componentsPath,
  hooksPath,
  utilsPath,
}: {
  cwd: string
  template: InitTemplate
  alias: string
  componentsPath: string
  hooksPath: string
  utilsPath: string
}) {
  const tsconfigPath = path.join(cwd, template === "vite" ? "tsconfig.app.json" : "tsconfig.json")

  if (!fs.existsSync(tsconfigPath)) return

  const tsconfig = parseJsonc(await fs.readFile(tsconfigPath, "utf8")) as {
    compilerOptions?: Record<string, unknown>
  }

  tsconfig.compilerOptions ??= {}

  const paths = ((tsconfig.compilerOptions.paths ?? {}) as Record<string, string[]>)
  paths[`${alias}/*`] = [getAliasTargetPath(template, componentsPath, hooksPath, utilsPath)]
  tsconfig.compilerOptions.paths = paths

  await fs.writeJson(tsconfigPath, tsconfig, { spaces: 2 })
}

async function ensureViteAlias({
  cwd,
  alias,
}: {
  cwd: string
  alias: string
}) {
  const viteConfigPath = path.join(cwd, "vite.config.ts")
  if (!fs.existsSync(viteConfigPath)) return

  const currentContent = await fs.readFile(viteConfigPath, "utf8")
  const importLine = `import path from 'node:path'`
  const tailwindImportLine = `import tailwindcss from '@tailwindcss/vite'`
  const resolveBlock = `  resolve: {\n    alias: {\n      '${alias}': path.resolve(process.cwd(), 'src'),\n    },\n  },`
  const aliasEntry = `      '${alias}': path.resolve(process.cwd(), 'src'),`

  let nextContent = currentContent

  if (!/import\s+path\s+from\s+["']node:path["']/.test(nextContent)) {
    nextContent = `${importLine}\n${nextContent}`
  }

  if (!/from\s+["']@tailwindcss\/vite["']/.test(nextContent)) {
    nextContent = `${tailwindImportLine}\n${nextContent}`
  }

  if (!/plugins\s*:\s*\[[\s\S]*?tailwindcss\s*\(/.test(nextContent)) {
    if (/plugins\s*:\s*\[/.test(nextContent)) {
      nextContent = nextContent.replace(/plugins\s*:\s*\[/, (match) => `${match}tailwindcss(), `)
    } else if (nextContent.includes("export default defineConfig({")) {
      nextContent = nextContent.replace("export default defineConfig({", "export default defineConfig({\n  plugins: [tailwindcss()],")
    }
  }

  if (nextContent.includes(`'${alias}': path.resolve(process.cwd(), 'src')`) || nextContent.includes(`"${alias}": path.resolve(process.cwd(), "src")`)) {
    if (nextContent !== currentContent) await fs.writeFile(viteConfigPath, nextContent)
    return
  }

  if (/alias\s*:\s*\{/.test(nextContent)) {
    nextContent = nextContent.replace(/alias\s*:\s*\{/, (match) => `${match}\n${aliasEntry}`)
  } else if (/resolve\s*:\s*\{/.test(nextContent)) {
    nextContent = nextContent.replace(/resolve\s*:\s*\{/, (match) => `${match}\n    alias: {\n${aliasEntry}\n    },`)
  } else if (nextContent.includes("export default defineConfig({")) {
    nextContent = nextContent.replace("export default defineConfig({", `export default defineConfig({\n${resolveBlock}`)
  } else {
    logger.warn("vite.config.ts ichida defineConfig topilmadi; alias faqat tsconfigga yozildi.")
  }

  if (nextContent !== currentContent) {
    await fs.writeFile(viteConfigPath, nextContent)
  }
}

const templateDefaults: Record<InitTemplate, Omit<InitResponse, "installDeps" | "writeThemeCss">> = {
  vite: {
    alias: "@",
    componentsPath: "src/components",
    uiPath: "src/components/ui",
    hooksPath: "src/hooks",
    utilsPath: "src/lib/utils.ts",
    globalCssPath: "src/index.css",
  },
  next: {
    alias: "@",
    componentsPath: "components",
    uiPath: "components/ui",
    hooksPath: "hooks",
    utilsPath: "lib/utils.ts",
    globalCssPath: "app/globals.css",
  },
}

function getTemplateDefaults(cwd: string, template: InitTemplate): Omit<InitResponse, "installDeps" | "writeThemeCss"> {
  const defaults = templateDefaults[template]

  if (template !== "next") return defaults

  const usesSrcApp = fs.existsSync(path.join(cwd, "src", "app"))
  if (!usesSrcApp) return defaults

  return {
    ...defaults,
    componentsPath: "src/components",
    uiPath: "src/components/ui",
    hooksPath: "src/hooks",
    utilsPath: "src/lib/utils.ts",
    globalCssPath: fs.existsSync(path.join(cwd, "src", "app", "globals.css"))
      ? "src/app/globals.css"
      : defaults.globalCssPath,
  }
}

function getConfiguredDefaults(
  defaults: Omit<InitResponse, "installDeps" | "writeThemeCss">,
  config?: TembroConfig,
): Omit<InitResponse, "installDeps" | "writeThemeCss"> {
  if (!config) return defaults

  return {
    ...defaults,
    alias: config.alias ?? defaults.alias,
    componentsPath: config.paths?.components ?? config.componentsPath ?? defaults.componentsPath,
    uiPath: config.paths?.ui ?? defaults.uiPath,
    hooksPath: config.paths?.hooks ?? defaults.hooksPath,
    utilsPath: config.utilsPath ?? defaults.utilsPath,
    globalCssPath: config.globalCssPath ?? config.cssPath ?? defaults.globalCssPath,
  }
}

function assertProjectPath(cwd: string, value: string, label: string) {
  if (path.isAbsolute(value)) {
    throw new Error(`${label} project ichidagi relative path bo‘lishi kerak: ${value}`)
  }

  const resolved = path.resolve(cwd, value)
  const relative = path.relative(cwd, resolved)
  if (relative.startsWith("..") || path.isAbsolute(relative)) {
    throw new Error(`${label} project tashqarisiga chiqmasligi kerak: ${value}`)
  }
}

function detectTemplate(cwd: string, packageJsonPath: string): InitTemplate {
  const packageJson = fs.readJsonSync(packageJsonPath) as {
    dependencies?: Record<string, string>
    devDependencies?: Record<string, string>
  }
  const deps = { ...packageJson.dependencies, ...packageJson.devDependencies }
  const hasNextConfig = ["next.config.js", "next.config.mjs", "next.config.ts"].some((fileName) =>
    fs.existsSync(path.join(cwd, fileName)),
  )
  const hasViteConfig = ["vite.config.js", "vite.config.mjs", "vite.config.ts"].some((fileName) =>
    fs.existsSync(path.join(cwd, fileName)),
  )

  if (deps.next || hasNextConfig) return "next"
  if (deps.vite || hasViteConfig) return "vite"

  return "vite"
}

function resolveTemplate(value: string | undefined, cwd: string, packageJsonPath: string): InitTemplate {
  if (value === "next" || value === "vite") return value

  const detectedTemplate = detectTemplate(cwd, packageJsonPath)
  if (value) {
    logger.warn(`Unknown template '${value}'. Falling back to ${detectedTemplate} defaults.`)
  }
  return detectedTemplate
}

function getInstalledPackages(cwd: string) {
  const packageJsonPath = path.join(cwd, "package.json")
  const packageJson = fs.readJsonSync(packageJsonPath) as {
    dependencies?: Record<string, string>
    devDependencies?: Record<string, string>
  }

  return new Set([
    ...Object.keys(packageJson.dependencies ?? {}),
    ...Object.keys(packageJson.devDependencies ?? {}),
  ])
}

export async function initCommand(options: InitCommandOptions = {}) {
  const cwd = process.cwd()
  const packageJsonPath = path.join(cwd, "package.json")

  if (!fs.existsSync(packageJsonPath)) {
    logger.error("package.json topilmadi / not found. Commandni React, Vite yoki Next project ichida ishlating.")
    process.exit(1)
  }

  const template = resolveTemplate(options.template, cwd, packageJsonPath)
  logger.info(`Template: ${template}${options.template ? "" : " (detected)"}`)
  const existingConfigPath = path.join(cwd, "tembro.json")
  const existingConfig = fs.existsSync(existingConfigPath)
    ? ((await fs.readJson(existingConfigPath)) as TembroConfig)
    : undefined
  const defaults = getConfiguredDefaults(getTemplateDefaults(cwd, template), existingConfig)
  const installedPackages = getInstalledPackages(cwd)
  const missingTailwindDependencies = templateTailwindDependencies[template].filter((pkg) => !installedPackages.has(pkg))

  const response = options.defaults
    ? ({
        installDeps: !options.skipInstall,
        installTailwindDeps: missingTailwindDependencies.length > 0,
        alias: defaults.alias,
        componentsPath: defaults.componentsPath,
        uiPath: defaults.uiPath,
        hooksPath: defaults.hooksPath,
        utilsPath: defaults.utilsPath,
        globalCssPath: defaults.globalCssPath,
        writeThemeCss: true,
      } satisfies InitResponse)
    : ((await prompts([
    {
      type: "confirm",
      name: "installDeps",
      message: "Theme va local source uchun minimal dependencylarni o‘rnataymi? / Install minimal theme dependencies?",
      initial: !options.skipInstall,
    },
    {
      type: missingTailwindDependencies.length > 0 ? "confirm" : null,
      name: "installTailwindDeps",
      message: `Tailwind paketlari topilmadi (${missingTailwindDependencies.join(", ")}). O‘rnataymi? / Install Tailwind packages?`,
      initial: true,
    },
    {
      type: "text",
      name: "alias",
      message: "Path alias qanday? / Path alias?",
      initial: defaults.alias,
    },
    {
      type: "text",
      name: "componentsPath",
      message: "Component root qayerda? / Component root?",
      initial: defaults.componentsPath,
    },
    {
      type: "text",
      name: "uiPath",
      message: "UI primitives qayerga yozilsin? / UI primitives path?",
      initial: defaults.uiPath,
    },
    {
      type: "text",
      name: "hooksPath",
      message: "Hooks qayerga yozilsin? / Hooks path?",
      initial: defaults.hooksPath,
    },
    {
      type: "text",
      name: "utilsPath",
      message: "utils.ts qayerga yozilsin? / utils.ts path?",
      initial: defaults.utilsPath,
    },
    {
      type: "text",
      name: "globalCssPath",
      message: "Theme tokenlar qaysi global CSS faylga yozilsin? / Global CSS path?",
      initial: defaults.globalCssPath,
    },
    {
      type: "confirm",
      name: "writeThemeCss",
      message: "Dark/light theme tokenlarni global CSS faylga yozaymi? / Write theme tokens?",
      initial: true,
    },
  ])) as InitResponse)

  const packageManager = detectPackageManager(cwd)

  logger.info(`Package manager: ${packageManager}`)

  if (!options.skipInstall && response.installDeps) {
    await installPackages({
      cwd,
      packageManager,
      packages: baseDependencies,
    })
  }

  if (!options.skipInstall && missingTailwindDependencies.length > 0 && response.installTailwindDeps) {
    await installPackages({
      cwd,
      packageManager,
      packages: missingTailwindDependencies,
      dev: true,
    })
  }

  const utilsPath = response.utilsPath || defaults.utilsPath
  const componentsPath = response.componentsPath || defaults.componentsPath
  const uiPath = response.uiPath || defaults.uiPath
  const hooksPath = response.hooksPath || defaults.hooksPath
  const globalCssPath = response.globalCssPath || defaults.globalCssPath

  for (const [label, value] of [
    ["componentsPath", componentsPath],
    ["uiPath", uiPath],
    ["hooksPath", hooksPath],
    ["utilsPath", utilsPath],
    ["globalCssPath", globalCssPath],
  ] as const) {
    assertProjectPath(cwd, value, label)
  }

  const config = {
    style: existingConfig?.style ?? "default",
    alias: response.alias || defaults.alias,
    componentsPath,
    utilsPath,
    cssPath: globalCssPath,
    globalCssPath,
    paths: {
      components: componentsPath,
      ui: uiPath,
      hooks: hooksPath,
      lib: path.dirname(utilsPath),
    },
  }

  await fs.writeJson(path.join(cwd, "tembro.json"), config, {
    spaces: 2,
  })

  const utilsFullPath = path.join(cwd, utilsPath)
  const componentsRootPath = path.join(cwd, componentsPath)
  const uiRootPath = path.join(cwd, uiPath)
  const hooksRootPath = path.join(cwd, hooksPath)
  await fs.ensureDir(path.dirname(utilsFullPath))
  await fs.ensureDir(componentsRootPath)
  await fs.ensureDir(uiRootPath)
  await fs.ensureDir(hooksRootPath)

  const componentBarrels = [
    path.join(componentsRootPath, "index.ts"),
    path.join(uiRootPath, "index.ts"),
    path.join(hooksRootPath, "index.ts"),
  ]

  for (const barrelPath of componentBarrels) {
    if (!fs.existsSync(barrelPath)) {
      await fs.writeFile(barrelPath, placeholderBarrel)
    }
  }

  if (!fs.existsSync(utilsFullPath)) {
    await fs.writeFile(
      utilsFullPath,
      `import { clsx, type ClassValue } from "clsx"
import { twMerge } from "tailwind-merge"

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}
`
    )
  }

  await ensureTsconfigAlias({
    cwd,
    template,
    alias: config.alias,
    componentsPath,
    hooksPath,
    utilsPath,
  })

  if (template === "vite") {
    await ensureViteAlias({
      cwd,
      alias: config.alias,
    })
  }

  if (response.writeThemeCss && globalCssPath) {
    const cssTarget = await upsertThemeCss({
      cwd,
      cssPath: globalCssPath,
      componentsPath,
    })

    logger.success(`Theme CSS yozildi / written: ${cssTarget}`)
  }

  logger.success("Tembro source-copy setup tayyor / initialized.")
  logger.info(`Component source root: ${componentsPath}`)
  logger.info(`UI primitives path: ${uiPath}`)
  logger.info(`Hooks path: ${hooksPath}`)
  logger.info("Componentlarni ko‘rish / list components:")
  logger.info(getCliNpxCommand("list"))
  logger.info("Component qo‘shish / add components:")
  logger.info(getCliNpxCommand("add button input"))
  if (missingTailwindDependencies.length > 0 && !response.installTailwindDeps) {
    logger.warn(`Tailwind paketlari hali o‘rnatilmadi: ${missingTailwindDependencies.join(", ")}`)
  }
  logger.info("Theme CSS ni yangilash / update theme CSS:")
  logger.info(getCliNpxCommand("theme"))

  if (options.showcase) {
    logger.info("Showcase qo‘shilmoqda: barcha componentlar + local workbench.")
    await addCommand(["showcase"], {
      overwrite: true,
      skipInstall: options.skipInstall,
    })
  } else {
    logger.info("To‘liq local workbench kerak bo‘lsa / full local workbench:")
    logger.info(getCliNpxCommand("init --showcase --defaults"))
  }
}
