import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"

export default function HomePage() {
  return (
    <main className="mx-auto flex min-h-screen max-w-2xl items-center px-6 py-16">
      <section className="w-full space-y-6 rounded-2xl border bg-white p-8 shadow-sm">
        <div className="space-y-2">
          <p className="text-sm font-medium text-neutral-500">Persistent consumer fixture</p>
          <h1 className="text-3xl font-semibold tracking-tight">Tembro works in Next.js App Router</h1>
          <p className="text-neutral-600">
            This page imports only local component source generated by the Tembro CLI.
          </p>
        </div>

        <div className="space-y-3">
          <Input aria-label="Workspace name" placeholder="Workspace name" />
          <Button type="button">Create workspace</Button>
        </div>
      </section>
    </main>
  )
}
