import { component, createShowcaseDemoRegistry } from "./create-demo"

export const registryQualityDemoRegistry = createShowcaseDemoRegistry([
  component("button", "Button", "actions", "Primary action surface for clicks, submit, and quick triggers in dashboard workflows."),
  component("input", "Input", "inputs", "Single-line text input for quick edits, queries, and form fields."),
  component("select", "Select", "inputs", "Select component with menu-driven single choice workflows."),
  component("combobox", "Combobox", "inputs", "Searchable local choice input for static datasets, labels, owners, and compact filters."),
  component("card", "Card", "display", "Container surface for dense dashboard sections, summaries, and interactive panels."),
  component("badge", "Badge", "display", "Compact status and category label with tone, variant, and inline usage states."),
  component("checkbox", "Checkbox", "inputs", "Boolean selection control for forms, tables, and filter groups."),
  component("dialog", "Dialog", "overlay", "Modal surface for confirmation, forms, and contextual workflows."),
  component("sidebar", "Sidebar", "layout", "Application navigation shell with active states, account area, and responsive collapse."),
  component("data-table", "DataTable", "data-table", "High density table with search, filters, rows, actions and pagination context."),
  component("date-picker", "DatePicker", "calendar", "Date picker surface for period and event selection."),
  component("date-range-picker", "DateRangePicker", "calendar", "Range picker surface for reporting windows and planning flows."),
  component("form-input", "FormInput", "form", "Input wrapper with RHF-ready metadata and helper text."),
  component("form-select", "FormSelect", "form", "Select wrapper for controlled local and async choice fields."),
  component("form-textarea", "FormTextarea", "form", "Textarea wrapper with helper, validation and consistent spacing."),
  component("form-switch", "FormSwitch", "form", "Boolean form control with shell-level label and hint handling."),
  component("form-date-picker", "FormDatePicker", "form", "Popover date picker wrapper with RHF integration."),
  component("form-date-range-picker", "FormDateRangePicker", "form", "Range date picker wrapper for planning and reporting flows."),
  component("alert-dialog", "AlertDialog", "overlay", "Destructive confirmation dialog with loading-ready action states."),
  component("drawer", "Drawer", "overlay", "Side panel for contextual details without leaving the page."),
  component("hover-card", "HoverCard", "overlay", "Hover and focus preview card for profile, metric, and link context."),

  component("pagination", "Pagination", "navigation", "Controlled page navigation with edge buttons and active state."),
  component("menubar", "Menubar", "navigation", "Accessible application menu bar for desktop-like command surfaces."),
  component("navigation-menu", "NavigationMenu", "navigation", "Accessible marketing and product navigation with viewport panels."),
  component("async-select", "AsyncSelect", "inputs", "Remote-loaded select for large server-backed option sets."),
  component("slider", "Slider", "inputs", "Single value range control for density, threshold, and score tuning."),
  component("range-slider", "RangeSlider", "inputs", "Two-handle slider for min/max filtering."),
  component("number-field", "NumberField", "inputs", "Stepper-backed numeric input with min, max, step, scrub area and controlled value support."),
  component("rating", "Rating", "inputs", "Compact score input for feedback and review flows."),
  component("otp-input", "OtpInput", "inputs", "One-time code entry with fixed-length slots."),
  component("inline-editable", "InlineEditable", "inputs", "Inline editing primitive for dense tables and configuration rows."),
  component("tag-input", "TagInput", "inputs", "Tokenized text input for labels, skills, and quick filters."),
  component("toggle-group", "ToggleGroup", "inputs", "Single or multi-select toggle group for compact mode, formatting and filter controls."),

  component("progress", "Progress", "display", "Linear progress with label, value formatter, tone and indeterminate state."),
  component("timeline", "Timeline", "display", "Vertical or horizontal event stream for workflow history."),
  component("activity-feed", "ActivityFeed", "display", "Operational activity stream with aligned connectors, metadata, and actions."),
  component("kanban", "KanbanBoard", "display", "DnD project board with WIP limits, selection, rich cards, and controlled move policies."),
  component("chat", "Chat", "display", "Conversation list, messages, attachments, status, typing, and composer primitives for support workspaces."),
  component("rich-text-editor", "RichTextEditor", "display", "Configurable rich editor with grouped toolbar, links, blocks, and document counts."),
  component("status-dot", "StatusDot", "display", "Tiny live status indicator with optional pulse animation."),
  component("notification-center", "NotificationCenter", "display", "Compact activity and notifications stream."),
  component("status-legend", "StatusLegend", "display", "Explain status meaning and counts in a compact legend."),

  component("action-menu", "ActionMenu", "actions", "Compact dropdown action menu for rows and cards."),
  component("button-group", "ButtonGroup", "actions", "Grouped action buttons for view switching and compact controls."),
  component("toolbar", "Toolbar", "actions", "Composable toolbar primitive with grouped buttons, separators, links, inputs and orientation support."),
  component("quick-action-grid", "QuickActionGrid", "actions", "Action launcher grid for dense dashboard shortcuts."),
  component("filter-bar", "FilterBar", "actions", "Search, filters, active-count and reset actions in one toolbar."),

  component("alert", "Alert", "feedback", "Inline feedback banner for success, warning, info, and error states."),
  component("toast", "ToastProvider", "feedback", "Provider and hook for transient success, warning, loading, and promise-driven messages."),
  component("state-view", "StateView", "feedback", "Route, inline, empty, loading, success and error states with next actions."),
  component("empty-state", "EmptyState", "patterns", "Focused empty and error state with clear next actions."),

  component("calendar", "Calendar", "calendar", "Single month calendar surface for date picker and scheduling flows."),

  component("file-upload", "FileUpload", "upload", "Full file upload surface with dropzone, action button and helper text."),
  component("image-upload", "ImageUpload", "upload", "Image upload pattern with preview-oriented copy."),

  component("stepper", "Stepper", "wizard", "Clickable step navigation for multi-step forms."),
  component("wizard", "Wizard", "wizard", "Stepper, content and footer controls combined into one workflow."),

  component("breadcrumbs", "Breadcrumbs", "layout", "Route context trail with overflow collapse and custom link rendering."),
])
