import { component, createShowcaseDemoRegistry } from "./create-demo"

export const registryQualityDemoRegistry = createShowcaseDemoRegistry([
  component("button", "Button", "actions", "Primary action surface for clicks, submit, and quick triggers in dashboard workflows."),
  component("input", "Input", "inputs", "Single-line text input for quick edits, queries, and form fields."),
  component("select", "Select", "inputs", "Select component with menu-driven single choice workflows."),
  component("dialog", "Dialog", "overlay", "Modal surface for confirmation, forms, and contextual workflows."),
  component("data-table", "DataTable", "data-table", "High density table with search, filters, rows, actions and pagination context."),
  component("date-picker", "DatePicker", "calendar", "Date picker surface for period and event selection."),
  component("form-input", "FormInput", "form", "Input wrapper with RHF-ready metadata and helper text."),
  component("form-select", "FormSelect", "form", "Select wrapper for controlled local and async choice fields."),
  component("form-textarea", "FormTextarea", "form", "Textarea wrapper with helper, validation and consistent spacing."),
  component("form-switch", "FormSwitch", "form", "Boolean form control with shell-level label and hint handling."),
  component("form-date-picker", "FormDatePicker", "form", "Popover date picker wrapper with RHF integration."),
  component("form-date-range-picker", "FormDateRangePicker", "form", "Range date picker wrapper for planning and reporting flows."),
  component("dialog-actions", "DialogActions", "overlay", "Modal footer action row with cancel, secondary and primary actions."),
  component("alert-dialog", "AlertDialog", "overlay", "Destructive confirmation dialog with loading-ready action states."),
  component("drawer", "Drawer", "overlay", "Side panel for contextual details without leaving the page."),

  component("pagination", "Pagination", "navigation", "Controlled page navigation with edge buttons and active state."),
  component("nav-tabs", "NavTabs", "navigation", "Navigation tabs for switching related document sections."),
  component("anchor-nav", "AnchorNav", "navigation", "Section jump navigation for long detail pages."),
  component("page-tabs", "PageTabs", "navigation", "Top-level page tab strip for route-sized sections."),
  component("stepper-tabs", "StepperTabs", "navigation", "Step-like tabs for setup and onboarding progress."),

  component("password-input", "PasswordInput", "inputs", "Password field with visibility toggle and secure autocomplete defaults."),
  component("number-input", "NumberInput", "inputs", "Numeric entry for counts, thresholds, and reporting controls."),
  component("phone-input", "PhoneInput", "inputs", "Phone input with stable raw and masked value handling."),
  component("money-input", "MoneyInput", "inputs", "Currency entry for billing, finance and KPI editing flows."),
  component("date-input", "DateInput", "inputs", "Single-date field for compact forms and filter bars."),
  component("date-range-input", "DateRangeInput", "inputs", "Date range surface for reporting and booking windows."),
  component("simple-select", "SimpleSelect", "inputs", "Static local-option select for dashboards and settings forms."),
  component("async-select", "AsyncSelect", "inputs", "Remote-loaded select for large server-backed option sets."),
  component("combobox", "Combobox", "inputs", "Searchable local choice input for reassignment and command-like selection."),
  component("slider", "Slider", "inputs", "Single value range control for density, threshold, and score tuning."),
  component("range-slider", "RangeSlider", "inputs", "Two-handle slider for min/max filtering."),
  component("rating", "Rating", "inputs", "Compact score input for feedback and review flows."),
  component("otp-input", "OtpInput", "inputs", "One-time code entry with fixed-length slots."),
  component("color-input", "ColorInput", "inputs", "Theme and accent color field with native color selection."),
  component("inline-editable", "InlineEditable", "inputs", "Inline editing primitive for dense tables and configuration rows."),
  component("tag-input", "TagInput", "inputs", "Tokenized text input for labels, skills, and quick filters."),

  component("description-list", "DescriptionList", "display", "Structured key-value details for entity, invoice and profile pages."),
  component("progress", "Progress", "display", "Linear progress with label, value formatter, tone and indeterminate state."),
  component("progress-circle", "ProgressCircle", "display", "Compact circular progress for sidebars and status cards."),
  component("timeline", "Timeline", "display", "Vertical or horizontal event stream for workflow history."),
  component("status-dot", "StatusDot", "display", "Tiny live status indicator with optional pulse animation."),
  component("user-card", "UserCard", "display", "User summary row with avatar, metadata and actions."),
  component("delta-badge", "DeltaBadge", "display", "Compact positive, negative, and risk deltas for metric summaries."),
  component("entity-header", "EntityHeader", "display", "Top summary row for a customer, invoice, or workspace."),
  component("notification-center", "NotificationCenter", "display", "Compact activity and notifications stream."),
  component("entity-card", "EntityCard", "display", "Structured summary card with title, meta, state and actions."),
  component("file-card", "FileCard", "display", "Compact file summary with state and actions."),
  component("data-list", "DataList", "display", "Readable title and description rows for compact operational lists."),
  component("status-legend", "StatusLegend", "display", "Explain status meaning and counts in a compact legend."),
  component("trend-card", "TrendCard", "display", "Metric summary card with trend context."),
  component("comparison-card", "ComparisonCard", "display", "Compare current and previous values in one compact card."),

  component("action-menu", "ActionMenu", "actions", "Compact dropdown action menu for rows and cards."),
  component("button-group", "ButtonGroup", "actions", "Grouped action buttons for view switching and compact controls."),
  component("quick-action-grid", "QuickActionGrid", "actions", "Action launcher grid for dense dashboard shortcuts."),
  component("filter-chips", "FilterChips", "actions", "Inline active filter summaries with clear and remove actions."),
  component("data-table-saved-filters", "SavedFilterSelect", "actions", "Saved filter chips and quick view controls."),
  component("filter-bar", "FilterBar", "actions", "Search, filters, active-count and reset actions in one toolbar."),
  component("command-palette", "CommandPalette", "actions", "Keyboard command surface for global navigation and actions."),

  component("app-header", "AppHeader", "layout", "Sticky product header with left, center and right slots."),
  component("section-header", "SectionHeader", "layout", "Reusable section title block with actions and metadata."),
  component("stat-card", "StatCard", "layout", "Dashboard stat card for KPI, trend and helper text."),

  component("alert", "Alert", "feedback", "Inline feedback banner for success, warning, info, and error states."),
  component("page-state", "PageState", "feedback", "Full-page completion or blocked state with next actions."),

  component("data-table-pagination", "DataTablePagination", "data-table", "Pagination control used by DataTable pages."),
  component("data-table-toolbar", "DataTableToolbar", "data-table", "Toolbar surface for DataTable search, filters and actions."),
  component("data-table-column-visibility-menu", "DataTableColumnVisibilityMenu", "data-table", "Column visibility menu pattern for table views."),
  component("data-table-select-column", "DataTableSelectColumn", "data-table", "Selection column pattern for bulk table workflows."),
  component("data-table-sortable-header", "DataTableSortableHeader", "data-table", "Sortable header trigger with clear visual state."),
  component("data-table-row-actions", "DataTableRowActions", "data-table", "Row action menu for inspect, duplicate and archive operations."),
  component("data-table-actions-column", "DataTableActionsColumn", "data-table", "Reusable actions column for DataTable definitions."),
  component("data-table-bulk-actions", "DataTableBulkActions", "data-table", "Bulk action bar for selected rows."),
  component("data-table-view-presets", "DataTableViewPresets", "data-table", "Saved table view presets for operational dashboards."),

  component("calendar", "Calendar", "calendar", "Single month calendar surface for date picker and scheduling flows."),

  component("file-upload", "FileUpload", "upload", "Full file upload surface with dropzone, action button and helper text."),
  component("image-upload", "ImageUpload", "upload", "Image upload pattern with preview-oriented copy."),
  component("file-dropzone", "FileDropzone", "upload", "Lightweight file dropzone primitive for custom upload flows."),

  component("stepper", "Stepper", "wizard", "Clickable step navigation for multi-step forms."),
  component("wizard", "Wizard", "wizard", "Stepper, content and footer controls combined into one workflow."),

  component("resource-page", "ResourcePage", "patterns", "Full resource index page shell for admin dashboards."),
  component("resource-detail-page", "ResourceDetailPage", "patterns", "Detail page shell with title, metadata and sections."),
])
